#MenuTitle: Spanish
# -*- coding: utf-8 -*-
# by Pedro Arilla
from __future__ import division, print_function, unicode_literals
__doc__="""
Opens a new tab and outputs Real* Spanish text.

All texts are property of their author(s).
"""

import GlyphsApp, time, random
Glyphs.clearLog()
print("New tab with Real* Spanish text @ " + time.strftime("%H:%M:%S"))

dictionary = [
    "Corría el año 1997, y la ciencia ficción todavía estaba de resaca por los futuros oscuros y lluviosos que caracterizaron al ciberpunk, con películas como Blade runner fijando un tono melancólico que muchos otros cineastas quisieron replicar con mayor o menor fortuna, habilidad y recursos económicos.",
    "¿Cómo le ha marcado su lugar de nacimiento (y dónde se ha criado) como persona y escritora?",
    "Cuando antes me refería por ejemplo a esos años 70 y 80 en la Margen izquierda, de las crisis de la desindustrialización, con un 50% de paro juvenil, un consumo de heroína disparado, etc., estoy hablando de violencia estructural, económica y política.",
    "“Contra el tabú. Por esa libertad. Por el coraje del suicida. Como homenaje”.",
    "Chantal Maillard cuenta que en junio del 2017 recibió Los habitados de Piedad Bonnett",
    "Los versos de Bonett eran: Quién vio lo que no vi, / a mí me pertenece: / tú como una ave inversa que se entrega, / oscura y sin plumaje, / derrotada. Al leerlos, Chantal sintió que estas palabras iban en busca de sus propios versos: Los ojos en las estrellas.../ ¿había nubes? / Pájaro de alas rotas / Mi hijo.",
    "El poeta italiano/malagueño Ángelo Néstore es amigo de Chantal Maillard, además de un considerado escritor como así demuestra en Hágase mi voluntad (Editorial Pretextos, Premio Internacional de Poesía Emilio Prados).",
    "Lo cierto es que nadie ha divulgado esas misivas, mientras que las 92 cartas que Emilia mandó a su amigo-amante entre 1883 y 1915 no solo se han conservado, sino que fueron publicadas en 2003 por la editorial Turner con el título de Miquiño mío.",
    "En cuanto a porcentaje de voto, la derecha suma un 44,8% —36,7 del PP y 8,2 de Vox—.",
    "Ángel Gabilondo continúa como el candidato con mejor valoración (5,6) por delante de Mónica García (5,3).",
    "Asimismo, se apunta a que la ampliación hasta 2025 se extiende a toda la superficie de La Remonta, aproximadamente 285.000 metros cuadrados de superficie, quedando excluidas siempre y en todo caso la zona de viviendas.",
    "Tanto Tebas como el resto de presidentes que han participado en la comparecencia han abogado por seguir en la vía de una reforma de la máxima competición europea, como aprobó este lunes la UEFA.",
    "«Vamos a seguir trabajando», incidió.",
    "El recorte de la plantilla afecta al 16% de los trabajadores, siendo 3.000 de ellos de la red de oficinas y las 800 restantes de los servicios centrales.",
    "Al contrario del resto de bancos, BBVA había evitado en los últimos años formalizar un ERE en su plantilla.",
    "¿Imaginas a Glovo, Uber, Bizum y tu banco en una sola app?",
    "La semana pasada se anunció la salida a Bolsa de Grab, una aplicación nacida en Singapur y presente en el sudeste asiático —Malasia, Filipinas, Vietnam, Camboya, Tailandia, Indonesia y Myanmar— que hace muchísimas cosas.",
    "A saber: te trae la comida a domicilio (como Just Eat), la compra y los paquetes (como Glovo), te permite reservar taxis, taxis compartidos e incluso minibuses para ir de un sitio a otro (como Uber y Cabify), pagar en las tiendas (como tu banco) y enviar dinero a tus contactos (como Bizum).",
    "No puede fallar.",
    "El directivo ejerce como vicepresidente desde el reciente nombramiento de Belén Gualda como presidenta del hólding público.",
    "El supuesto ‘caravaggio’ estaba en manos de una familia de gran tradición artística.",
    "¡Casi 100.000 personas han estado tres meses o más de baja por el coronavirus!",
    "De los que sí tienen ya determinado el importe, cuatro superan el millón de euros: HM Montepríncipe (1.462.092,87 euros); HM Puerta del Sur (1.347.120,87); Hospital Fuensanta (1.265.087); y Beata María Ana de Jesús (1.161.755,99).",
    "¿Cuál sería la compensación de las empresas privadas por ceder sus instalaciones y profesionales a los pacientes de la sanidad pública?",
    "“Los titulares de los centros afectados presentaron escritos de reclamación acompañados de un informe pericial [el que realizó KPMG]” que detallaba lo que les había supuesto la atención a esos 1.723 pacientes.",
    "Por lo pronto, la incidencia acumulada a 14 días, aunque muy elevada —232,55 casos por 100.000 habitantes—, apenas reflejó este jueves un ligero ascenso de tres puntos después de dos días estancada.",
    "Los de Milwaukee estuvieron liderados por Giannis Antetokounmpo, que pese a firmar una primera parte un tanto discreta tomó las riendas del encuentro en la segunda y terminó dominando con 27 puntos, 16 rebotes y 6 asistencias.",
    "Su presencia en pista se saldó con un parcial de +25 para los suyos, y con sus canastas fue el gran responsable de aplacar los intentos de los 76ers de reengancharse al partido tras el descanso.",
    "Oculus anuncia Carve Snowboarding, del programador de 1080° Snowboarding.",
    "«Mientras hacíamos Celeste, básicamente tuiteábamos cualquier cosa medio interesante en la que trabajábamos día a día, cuando nos apetecía compartir algo», escribe Maddy Thorson.",
    "El parque nacional de Yellowstone —en inglés: Yellowstone National Park— es un parque nacional ubicado en los estados de Wyoming, Montana e Idaho, en Estados Unidos, y cuya superficie abarca 3468,4 mi² (8983,2 km²).",
    "La Unesco lo nombró Patrimonio de la Humanidad en 1978.",
    "Aproximadamente, el 96 % del territorio del Yellowstone está ubicado en el estado de Wyoming, mientras que el pequeño área restante queda repartido entre Montana (3 %) e Idaho (1 %).",
    "La temperatura máxima alcanzada en el parque ha sido de 99 °F (37,2 °C), registrada en el 2002, mientras que la más baja fue de −66 °F (−54,4 °C), hallada en 1933.",
    "Después de ser suspendido por Florida, Williams decidió presentarse al Draft de la NBA de 1998.",
    "El 19 de agosto de 2009 fichó por los Orlando Magic por una temporada, así es como se confirma la vuelta de Chocolate Blanco a las canchas de basket.",
    "Williams se retiró de la NBA con unos promedios de 11.7 puntos y 6.5 asistencias.",
    "John Van Meter, un comerciante indio, fue a la parte norte en 1725.",
    "En 1661, Carlos II le dio a esa compañía la franja comprendida entre el Potomac y Rappahannock,conocida como Northern Neck.",
    "La población no era homogénea, pues gran parte de la inmigración vino de Pensilvania e incluyó alemanes, protestantes escoceses-irlandeses, y colonos de los estados más al norte.",
    "La «pata conejo», Polycarpaea divaricata, es una especie de fanerógama de la familia de las cariofiláceas.",
    "Tiene un reconocible aire popular y aflamencado.",
    "Luego comenzó dirigiendo al plantel profesional en la Segunda División 1999-2001.",
    "Veľké Kostoľany es un municipio del distrito de Piešťany en la región de Trnava, Eslovaquia, con una población estimada a final del año 2017 de 2764 habitantes.",
    "Se encuentra en Nueva Guinea.",
    "En 1937 la BSA firmó un acuerdo con la fábrica de armas Zbrojovka Brno, que le permitía fabricar bajo licencia la ametralladora ZB-53 calibre 7,92 en el Reino Unido.",
    "Los modelos iniciales Mark I, Mark II, y Mark II* de la Besa fueron declarados obsoletos en 1951 y todos los modelos Mark II fueron modificados a Mark III*.",
    "El Decreto Ley 14977 agrupa los feriados en dos categorías: «feriados nacionales de carácter tradicional», que comprende el 1 de enero, 6 de enero, lunes y martes de Carnaval, Semana de Turismo, 1 de mayo, 2 de noviembre y 25 de diciembre; y «feriados nacionales de exaltación y conmemoración patriótica», que incluye el 19 de abril, 18 de mayo, 19 de junio, 18 de julio, 25 de agosto y 12 de octubre.",
    "Badawi fue educado en la exclusiva escuela al-Saidiya de Guiza, donde se graduó con el número dos.",
    "Su tesis doctoral, El problema de la muerte en El existencialismo, fue supervisada en 1944 por Alexandre Koyré",
    "La caballería ligera de este tipo comenzó a ser usada durante las guerras polaco-suecas de finales del siglo XVI. A comienzos del siglo XVII, la caballería hakkapeliitta dirigida por el mariscal de campo Jacob De la Gardie participó en campañas contra Polonia y Rusia.",
    "Así lo certificó ayer la oficina estadística europea, Eurostat, al confirmar que el déficit público español saltó del 2,9% del PIB a cierre de 2019 al 11% en 2020, el mayor desequilibrio entre ingresos y gastos de toda la UE.",
    "Bank of America, Barclays, CaixaBank BPI, HSBC, ING, IMI, Intesa Sanpaolo y Santander han estado en un segundo lugar.",
    "¿Y cuánto tendría que haber tributado? ",
    "Y con independencia de que estén en gananciales, la declaración en el IRPF o en el Impuesto de Sucesiones y Donaciones correspondería exclusivamente al esposo.",
    "Eso daría una cuota tributaria, haciendo un cálculo rápido, de unos 1.200.000 €",
    "No es posible olvidar en este sentido el papel de Juana de Castilla.",
    "Llega a GAME el nuevo MotoGP 21 disponible en PC, Playstation 4, Playstation 5, Xbox One, Xbox Serie X y Nintendo Switch.",
    "¡Toma tu posición en la parrilla de salida y prepárate para la experiencia más realista e inmersiva que ha ofrecido nunca un videojuego de MotoGP!",
    "Grand Theft Auto V: Premium Edition + 14,95€.",
    "Imagen 2.40:1 4K (2160p).",
    "Críticos: Todd McCarthy, John Powers y David Thomson.",
    "Compositor: Don Davis (música aislada).",
    "29 Marzo 2021.",
    "Nier Replicant PS4: 54,00 € (IVA incluído). Fecha de lanzamiento: 2021-04-23. Género: Acción, Rol/RPG.",
    "Hades Nintendo Switch: 32,99 € (IVA incluído). Fecha de lanzamiento: 2021/03/19. Género: Aventura.",
    "Recuerde que trabajamos de Lunes a Viernes y la compañía logística pasa a recoger los pedidos a las 16:00h (Correos Express) y a las 17:30h (Nacex).",
    "El Cliente podrá ejercitar su derecho de desistimiento cumplimentando y remitiendo el formulario de desistimiento por alguno de los siguientes medios: a la dirección de email info@tutiendadevideojuegos.com, por correo postal a la dirección C/Júpiter 28, 08228 Terrassa (Barcelona).",
    "Y todo ello con una alta velocidad (hasta 120 fps con salida de 120 Hz), potencia y rendimiento gracias a su CPU, GPU y SSD personalizadas con un sistema de E / S integrado que reescribe las reglas de lo que es capaz una consola PlayStation y que maximizan tus sesiones de juego con tiempos de carga casi instantáneos para los juegos instalados.",
    "Y por si fuera poco, las consolas PS5 admiten salida de 8K que te permiten jugar en pantallas de resolución de 4320p y, en juegos compatibles con Tempest 3D AudioTech, podrás vivir una experiencia de sonido en todas direcciones a través de tus auriculares con micrófono o altavoces de TV.",
    "CPU x86-64-AMD Ryzen™ “Zen 2”.",
    "USB Type-C® port (Super-Speed USB 10Gbps).",
    "Wi-Fi estándares: 802.11a,802.11b,802.11g, Wi-Fi 4 (802.11n), Wi-Fi 5 (802.11ac), Wi-Fi 6 (802.11ax).",
    "Mando inalámbrico (DualSense), Base, Cable HDMI, Cable USB, Cable de alimentación, SSD 825GB, Astro’s Playroom (juego preinstalado en la consola).",
    "La impresión con tipos de madera se desarrolló durante el siglo XIX a raíz de la expansión comercial, y por tanto publicitaria, que trajo consigo la era industrial, sobre todo en Estados Unidos.",
    "El formato OpenType SVG, usado en el proyecto, busca la mayor fiabilidad posible a la hora de reproducir detalladamente la riqueza de texturas y los matices de la impresión con tipos de madera, sobre todo en las imperfecciones, esas áreas de transición de grises tan delicadas y atractivas.",
    "Por ello, la web del proyecto incluye un breve tutorial para su uso en Photoshop, para, por ejemplo, cambiar las fuentes de color, ya que, al estar digitalizada como imagen, ha de hacerse usando, por ejemplo, con una capa de ajuste «color uniforme» y modo de fusión «color» en lugar del habitual selector de color. ",
    "Sin embargo, esta herramienta nació hace poco más de diez años, pero ¿quién la creó?,¿cuál fue el primer vídeo que se subió?",
    "Solo un año más tarde, esta plataforma fue vendida a Google Inc. por 1.650 millones de dólares.",
    "En el momento de la creación de la plataforma, Jawed Karin era el más joven de los tres creadores, tenía solo 26 años.",
    "Estas fotografías en blanco y negro fueron realizadas en 1932 y forman parte de un libro al que Blossfeldt tituló Urformen der Kunst, Wundergarten der Natur (Las formas originales del Arte, El jardín maravilloso de la Naturaleza).",
    "Según Sergio de León, Global Strategic Marketing and Digital Director de Loewe Perfumes: “Arte, naturaleza, piel y lifestyle español son los cuatro valores en los que se ancla nuestra nueva forma de comunicar. Cuatro valores que combinados te descubren la experiencia de Loewe y que hemos materializado en un rebranding en el que auténticas obras de arte visten nuestros packs”.",
    "Dos caminos muy distintos con resultados totalmente opuestos. ¿Qué opinas? ¿Brillante idea o diseño confuso?",
    "El Monte Albert fue llamado así en honor del príncipe Alberto de Sajonia-Coburgo-Gotha porque el geólogo Alexander Murray hizo la primera subida registrada a la montaña en el cumpleaños del Príncipe, el 26 de agosto de 1845.",
    "Juan Pío Membrado Ejerique (Belmonte de San José, 1851 – 1923), periodista y escritor bajoaragonés del Regeneracionismo.",
    "En 2005 fue publicado para Nintendo DS.",
    "Los siguientes peleadores obtuvieron premios extra de $50 000.",
    "Félix lleva una vida tranquila y sin sobresaltos en Andorra, adonde se ha trasladado para estar cerca de su hijo.",
    "Variimorda shiyakei es una especie de coleóptero de la familia Mordellidae.",
    "Habita en Vietnam.",
    "Pasó el resto de su vida en Zagreb con su mujer Sonya con quién se casó en Moscú en 1930.",
    "Obras expuestas en los museos de Barnaul, Tscheboksary, Taganrog, Rostow-am-Don, Jaroslawl y Krasnodar.",
    "Estudió en el Instituto Surikov de Moscú, con A. Osmiorkin, H. Maksímov, y P. Kotov hasta 1950.",
    "Dichas instituciones han sido ordenadas en tres listados diferentes: en el primero se consignan las universidades insertadas, es decir, siguiéndo un orden cronológico de acuerdo al año en que fueron otorgados sus documentos fundacionales (real provisión, real cédula y bula o breve pontificios); en el segundo van las universidades en funcionamiento continuo desde su fundación, es decir, aquellas consideradas actualmente las más antiguas, prescindiendo de aquellas extinguidas hasta el siglo XIX; y, en la tercera, los colegios mayores, instituciones que, de acuerdo a la normativa de la época, servían de alojamiento como internados a los estudiantes universitarios pero que, en numerosos casos, cumplieron la función de «facultades docentes» de las universidades a las cuales se hallaban adscritas.",
    "La cancha de Sphairistikè tenía forma de reloj de arena, más ancha en la línea de fondo que en la red.",
    "La propuesta la realizó Henry Jones, un escritor deportivo que publicaba constantemente en The Field bajo el sobrenombre de «Cavendish» y que se había unido al club en 1869.",
    "El deporte llegó a una popularidad tal que, el 14 de abril de 1877, el club fue renombrado, a sugerencia del miembro fundador John H. Hale, como el All England Croquet and Lawn Tennis Club (AEC&LTC).",
    "1º en la Bruselas-Opwijk.",
    "63º de la clasificación general.",
    "Al día siguiente, Rothstein, un tiburón de tarjeta conocida y tramposo, tiene 3l casino de Thompson por más de $90.000.",
    "Después, Thompson come con cuatro grandes figuras de la mafia, Arnold Rothstein (Michael Stuhlbarg) y Lucky Luciano (Vincent Piazza) de Nueva York y Big Jim Colosimo (Frank Crudele) y Johnny Torrio (Greg Antonacci) de Chicago, que están de acuerdo para empezar a comprar licor por envíos por vía marítima de Thompson.",
    "En su transmisión original a las 21:00 horas en Estados Unidos, Boardwalk Empire llegó a una audiencia de 4,81 millones de telespectadores.",
    "La serie presenta un gran elenco como sobrevivientes de un apocalipsis zombi, tratando de mantenerse con vida bajo la amenaza casi constante de ataques de los zombis sin conciencia, coloquialmente conocidos como «caminantes».",
    "La segunda serie derivada, The Walking Dead: World Beyond, se estrenará en 2020.",
    "«Me encanta trabajar con material original, específicamente porque tenemos una muy buena idea de lo que será la temporada 10», dijo Alpert.",
    "La página web oficial de la serie lanzó, justo antes del San Diego Comic-Con International 2010, una historieta basada en la edición n.º 1 del cómic original.",
    "En Rotten Tomatoes, la serie tiene una calificación promedio del 81%.",
    "Para la segunda temporada, el 80% de las 24 reseñas de Rotten Tomatoes fueron positivas, con un puntaje promedio de 8.08/10.",
    "«The Walking Dead: Season 4 (2013–2014)» (en inglés). Rotten Tomatoes. Archivado desde el original el 21 de agosto de 2014. Consultado el 10 de diciembre de 2013.",
    "Dufour, IX-1.",
    "Con 260 votos a favor de Morena, PT y Verde; 2 abstenciones y 167 votos en contra del PAN, PRI, PRD, MC y PES, se aprobó en lo general la Ley Orgánica del Poder Judicial de la Federación; se presentaron 553 reservas.",
    "“Qué tipo de noche vamos a vivir hoy? ¿La que va a discutir las leyes que van a fortalecer el Poder Judicial de la Federación? ¿O el artículo transitorio que va a minar la credibilidad de la democracia mexicana? La decisión está en todas y todos nosotros; hagamos lo correcto por la patria”, expuso.",
    "Muñoz Ledo: marranadas en Morena para imponer a Zaldívar.",
    "La renovación de votos de EU ayudó a que otros países actualizaran sus metas: Canadá anunció una baja de sus emisiones de entre 40% y 45% para 2030 con respecto a 2005, en lugar de 30% anterior.",
    "La actual —y siempre— decisión de congelar los precios de la canasta familiar tiene muchos desafíos para los funcionarios.",
    "En el BCRA la toman en cuenta y el directorio esta en deliberación constante: porque en caso de cumplirse esta predicción, el “Plan Otoño” puede saltar por los aires.",
    "¿Por qué en la segunda ola se habla de que hay más chicos internados?",
    "Si bien es raro que los niños hagan formas severas de la enfermedad por SARS-CoV-2, la búsqueda mundial de generar inmunidad de rebaño en las poblaciones a través de la vacunación (con la intención lógica de bloquear todos los callejones por los cuales circula el virus) es un plan que supone inmunizar, también, a niños y adolescentes.",
    "Cristina Kirchner tras la vacuna rusa, las internas porteñas y las entrevistas de la ministra.",
    "Entonces, vivía en la capital española y su ultimo lugar antes de venir a la Argentina, fue Boston, la capital de Massachusetts.",
    "Una asesora a la izquierda...",
    "Primero, fue porque estuvo en dudas la continuidad como ministro de Educación, Nicolás Trotta, (muy cercano a Santa María) quien rompió su largo silencio justamente en un reportaje con el diario Página/12, propiedad del cacique del SUTERH.",
    "Pandemia y explosión inmobiliaria.",
    "Allí, en el edificio Skyglass 2, una oficina a estrenar de 50 m² con atributos y servicios de calidad, más amenities comunes, se ofrece a US$100.000 más IVA.",
    "La Fundación El Libro, que organiza la Feria Internacional de Buenos Aires (postergada hasta nuevo aviso por la segunda ola de contagios) invita a los lectores a compartir en redes sociales con el hashtag #MiDíaDelLibro una imagen con su título de cabecera, librería preferida, escritor o escritora favorita o del libro que se está leyendo.",
    "El libro que más he regalado probablemente sea Nueve cuentos de J. D. Salinger.",
    "¡Dios mío! ¿Un instante de felicidad no basta a una vida humana?",
    "#ComparteCultura",
    "Una comunidad que no para de crecer en YouTube, Instagram y TikTok.",
    "Se propuso leer el primer tomo de Juego de tronos, de George R. R. Martin, al que definió como “un termotanque” porque tiene más de 800 páginas.",
    "“Todavía no leí nada de Shakespeare”.",
    "Y lo primero que hizo fue limpiar unas armas que habían sido de sus bisabuelos, que, tomadas de orín y llenas de moho, luengos siglos había quecestaban puestas y olvidadas en un rincón.",
    "¡Oh tú, sabio encantador, quienquiera que seas, a quien ha de tocar el ser coronista desta peregrina historia, ruégote que no te olvides de mi buen Rocinante, compañero eterno mío en todos mis caminos y carreras!",
    "¿Irme yo con él? —dijo el muchacho—. Mas, ¡mal año! No, señor, ni por pienso; porque, en viéndose solo, me desuelle como a un San Bartolomé.",
    "¡Malditos, digo, sean otra vez y otras ciento estos libros de caballerías, que tal han parado a vuestra merced!",
    "Así es verdad —dijo el cura—, y por esa razón se le otorga la vida por ahora. Veamos esotro que está junto a él.",
    "¡Oh señora de mi alma, Dulcinea, flor de la fermosura, socorred a este vuestro caballero, que, por satisfacer a la vuestra mucha bondad, en este riguroso trance se halla!",
    "Por la puerta de mi casa—en las Cuatro Esquinas—pasaban las procesiones de la Semana Santa, una Semana Santa famosa: «Semana Santa en León y Corpus en Guatemala»—; y las calles se adornaban con arcos de ramas verdes, palmas de cocotero, flores de corozo, matas de plátanos o bananos, disecadas aves de colores, papel de China picado con mucha labor; y sobre el suelo se dibujaban alfombras que se coloreaban, expresamente, con serrín de rojo brasil o cedro, o amarillo «mora»; con trigo reventado, con hojas, con flores, con desgranada flor de «coyol».",
    "¡Fidelina, Rafaela, Julia, Mercedes, Narcisa, María, Victoria, Gertrudis!, recuerdos, recuerdos suaves.",
    "Cuando la luna iba menguando, retornaban las familias a la ciudad.",
    "«¡Jesús!, ¡Jesús!, ¡Jesús!» hasta mil; y a veces se perdía la cuenta y había que volver a empezar.",
    "Como se ve, era la iniciación de un nacido aeda.",
    "Cayó en mis manos un libro de masonería, y me dió por ser masón, y llegaron a serme familiares Hiram, el Templo, los caballeros Kadosh, el mandil, la escuadra, el compás, las baterías y toda la endiablada y simbólica liturgía de esos terribles ingenuos.",
    "A la sazón, estaba reunido el Congreso.",
    "Un día dije a mis amigos:—«Me caso». La carcajada fué homérica.",
    "¿Para dónde? Para cualquier parte. Mi idea era irme a los Estados Unidos.",
    "Por recomendación de aquel distinguido caballero entré inmediatamente en la redacción de «La Época», que dirigía el señor Eduardo Mac-Clure, y desde ese momento me incorporé a la joven intelectualidad de Santiago.",
    "Viejo republicano, amigo de Salmerón y de Pí y Margall, creo que fué, durante la república, gobernador de Zaragoza.",
    "¡Qué ha de pasar!",
    "«En Villaverde—dicen sus hijos—no se hace política».",
    "No son los tales muchos, ni muy conocidos, pero los villaverdinos traen a cuento sus nombres, en toda ocasión, vengan o no vengan al caso.",
    "Una tarde muy calurosa de principios de julio, salió del cuartito que ocupaba, junto al techo de una gran casa de cinco pisos, un joven, que, lentamente y con aire irresoluto, se dirigió hacia el puente de K***.",
    "Esta vez él mismo se asombró, cuando estuvo en la calle, del temor de encontrar a su acreedora.",
    "Raskolnikoff no estaba habituado a la multitud, y, conforme hemos dicho, desde hacía algún tiempo evitaba las compañías de sus semejantes; pero de repente se sintió atraído hacia los hombres.",
    "¡Je, je, je!",
    "¡Ah, Dios mío! Batuchka, ¿sabe usted lo que son pruebas?",
    "Este corrió a abrir la ventana.",
    "«¿Es posible que siga mintiendo en este momento?», se preguntaba; y esforzábase para desechar esta idea, presintiendo el exceso de rabia loca a que podía impulsarle.",
    "Enterado de todos estos pormenores, Pedro Petrovitch tuvo una idea y entró pensativo en su habitación, o mejor dicho, en la de Andrés Semenovitch Lebeziatnikoff: acababa de saber que Raskolnikoff figuraba en el número de los invitados.",
    "¡Qué villanía!",
    "D. Francisco Goya y Lucientes nació en Fuentedetodos, Aragón, el dia 31 de Marzo de 1746: no se tienen noticias detalladas de su juventud, y solo se sabe que desde la edad de 13 años se dedicó al dibujo en Zaragoza bajo la dirección de D. José Luzan, y que, muy jóven aún, pasó á Roma donde continuó sus estudios.",
    "Grabó al agua fuerte además de la coleccion que hoy se publica otras tres que compondrán mas de doscientos cobres y pasó los últimos años de su vida dibujando constantemente.",
    "¡Oh vida, eternamente mal interpretada!",
    "Es la hora en que el pico erecto del viejo Aralar se arrebuja en un cendal de niebla.",
    "Al verlas pasar, especialmente si es lunes, algún joven boyero asoma al portal de la venta y lanza, rijoso y piropeante, un súbito grito: ¡aufá!...",
    "También me complace entrar abajo, a la taberna, y ver uno a uno a los bebedores.",
    "¡Arri, arri!... Su caballito de ancas finas es el más lindo del contorno. Pero la hermosa Cataliñ no monta en él. ¿Para qué? A ella le basta su fuerte, su rica juventud para bajar andando hasta la ciudad, tan pronto alumbra el día, y subir a la hora meridiana hasta el remoto caserío que está posado, realmente como un ave blanca en una gran pradera, al pie de una montaña.",
    "Posteriormente se estableció en Madrid, trabajando para Arturo Mélida, y al morir en 1890 el ceramista Guillermo Zuloaga (hermano de Daniel Zuloaga), le sustituyó en el cargo de maestro de taller de la Escuela de Artes y Oficios de Madrid, y adquirió más tarde el taller que los hermanos Zuloaga tenían en Vallehermoso.",
    "Tiene una Licenciatura de la Universidad de Harvard y un título PhD de la Universidad de Columbia.",
    "Es doctor en Derecho Canónico por el Angelicum.",
    "Hija de Marie-Jacques, marqués de Bréhan y vizconde de l'Isle, y de Marie-Jeanne-Angélique Delpech de Cailly, contrajo matrimonio el 8 de marzo de 1769 con Charles-René de Maillé de La Tour-Landry (1732-1791), duque de Maillé, con quien tuvo dos hijos: Charles-François-Armand, nacido el 26 de enero de 1770, y Charles-Jean, nacido el 24 de junio de 1771.",
    "En una expedición posterior fue formalmente adoptado en Detroit por el clan de Oso de los Kanien'kehá:ka (Mohawk) con el nombre “Eghnidal” por Karonghyontye (Cerro del capitán David), y descendió por el Misisipi hasta Nueva Orleans, desde donde regresó a Inglaterra.",
    "Annona muricata, la guanábana3 —nombre de origen taíno— o graviola4 es un árbol de la familia Annonaceae. Originario de Sudamérica, se cultiva por sus frutos comestibles en muchos países de clima tropical.",
    "Murió exiliado, en la ciudad de Sevilla, el 31 de diciembre de 1900, a los 63 años en estado de pobreza.",
    "Aynia pseudascaricida fue descrita por Harold E. Robinson y publicado en Proceedings of the Biological Society of Washington 101(4): 959. 1988.",
    "La Temporada 1974-75 fue la edición XXXIII del campeonato de liga de la Primera División en la denominada «época profesional» del fútbol mexicano.",
    "El actor que lo interpreta en la adaptación televisiva de Game of Thrones declara sobre su personaje: «Robb Stark es un joven que tiene que aprender muy rápido a ser un hombre y un líder [...] Está muy impregnado sobre las enseñanzas del honor y el deber que aprendió de su padre».",
    "Saint-Ouen-les-Vignes es una población y comuna francesa, situada en la región de Centro, departamento de Indre y Loira, en el distrito de Tours y cantón de Amboise.",
    "El álbum recibió críticas positivas de críticos musicales y, comercialmente, el álbum debutó en el número 103 en el US Billboard 200.",
    "«Why we think Collins Place will be the best address in Australia». The Age. 22 de agosto de 1978. p. 6. Consultado el 25 de abril de 2011.",
    "Day, Norman (10 de octubre de 1978). «New York lesson in merchandising». The Age. p. 2. Consultado el 25 de abril de 2011.",
    "Richard “Dick” Norris Williams II, más conocido como R. Norris Williams (Ginebra, 29 de enero de 1891 - Bryn Mawr, 2 de junio de 1968) fue un tenista estadounidense que se destacó principalmente en los años 1910.",
    "En 1914 logró su primer título en el US Championships, venciendo en una emocionante final a Maurice McLoughlin por 6-3 8-6 10-8, donde Williams contó con un maravilloso control de la pelota. Logró reconquistar el título en 1916, venciendo en la final a Bill Johnston.",
    "Jorge Cardona Márquez (Zaragoza, 2 de noviembre de 1987) es un deportista español que compite en tenis de mesa adaptado.1 Ganó tres medallas en los Juegos Paralímpicos de Verano entre los años 2008 y 2016.",
    "2018: Martín Piñol, por Superbaguet.",
    "Levante EMV, ed. (8 de noviembre de 2017). «Ximo Cerdà gana el XXII Vicent Silvestre de Narrativa Infantil de los Ciutat d'Alzira». Consultado el 10 de julio de 2018.",
    "El principal kami consagrado aquí es Tsukuyomi-no-Mikoto. El santuario se estableció en el año 593. La fiesta principal del santuario se celebra anualmente el 14 de agosto.",
    "Esta especie se encuentra amenazada de extinción debido a la destrucción de su hábitat natural.",
    "Manamendra-Arachchi, K. & Pethiyagoda, R. 2004. Philautus sordidus. 2006 IUCN Red List of Threatened Species. Consultado el 8 de enero de 2008.",
    "Forrester Research de Massachusetts estima que los ingresos por comercio electrónico B2B aumentarán de $ 109 mil millones en 1999 a $ 2,7 trillones en 2004.",
    "Esto representa aproximadamente el 25% del actual producto interno bruto de los Estados Unidos.",
    "(473032) 2015 HS71 es un asteroide perteneciente al cinturón de asteroides, descubierto el 24 de octubre de 2007 por el equipo del Mount Lemmon Survey desde el Observatorio del Monte Lemmon, Arizona, Estados Unidos.",
    "2015 HS71 está situado a una distancia media del Sol de 2,869 ua, pudiendo alejarse hasta 3,416 ua y acercarse hasta 2,323 ua. Su excentricidad es 0,190 y la inclinación orbital 11,11 grados. Emplea 1775 días en completar una órbita alrededor del Sol.",
    "Según el Tratado de Gueórguiyevsk firmado en 1783 y que puso al Reino de Kartli-Kajetia bajo protectorado ruso, el patriarca-catolicós de Georgia fue declarado miembro del Sínodo de la Iglesia ortodoxa rusa.",
    "Hallan, Joel Kenneth (6 de junio de 2010). «Synopsis of the described Coleoptera of the World». Biology Catalog de la Universidad de Texas A&M‎ (en inglés). Archivado desde el original el 2016. Consultado el 15 de enero de 2012.",
    "De ella se hicieron varias reimpresiones, la última de ellas significativamente en La Rochelle en 1620, y en 1619 apareció en Fráncfort una versión políglota, con los versos en francés, latín (en dos versiones), español, italiano, alemán, inglés y flamenco.8",
    "Núñez, Luis Pablo, «El español de los Emblemas cristianos (1619) de Georgette de Montenay y otras obras religiosas y emblemáticas plurilingües de los siglos XVI y XVII», Bulletin Hispanique, 111-1 (2009), pp. 219-243.",
    "Dado que la propiedad buscaba algo distinto a las realizaciones en acero generalizadas en América del Norte, se le pidió a Riccardo Morandi que diseñase un puente de hormigón.",
    "El puente de Kinnaird se completó en 1965 (aunque según algunas fuentes, fue terminado en 1960).",
    "Un estudio calcula que las ventas de audiolibros superan en España los 10 millones de euros y que el crecimiento anual es de un 30%.",
    "No es la única plataforma de suscripción que funciona en España, por supuesto. Kobo, Pódimo e Storytel son otras de las más populares.",
    "Según los datos del Ministerio de Cultura y Deporte, los datos de préstamo de audiolibros a través de eBiBlio pasaron de 13.058 en 2018 a 186.882 en 2020.",
    "¡No va a estar una pobre gallina todo el día incubando!",
    "WWF se une a Sofía Vergara y Marc Anthony en el film animado «Koati»",
    "La cinta, cuya fecha de estreno todavía se desconoce y en la que la actriz colombiana lleva mucho tiempo trabajando, cuenta ahora con el apoyo de la importante ONG ecologista, que ha aplaudido esta colaboración este jueves, cuando se celebra el Día del Planeta Tierra",
    "El daño ambiental que sufre el país ha reducido en las últimas décadas el caudal de muchas fuentes de agua como ríos y quebradas, según autoridades hondureñas.",
    "Barcelona, 22 abril (EFE).- El director del Programa Mundial de Malaria de la OMS, Pedro Alonso, ha afirmado este jueves que la COVID-19 no podrá erradicarse como enfermedad por tener su origen presuntamente en un reservorio animal y tener huéspedes animales.",
    "A pesar de ser una lengua milenaria con pocos hablantes y en peligro de extinción, el aragonés suscita cada vez más interés dentro y fuera de la Comunidad.",
    "Ahora se encuentra inmerso en un proyecto donde los aficionados del Real Zaragoza y el SD Huesca pueden ponerse al día de sus equipos hablando aragonés en Twitch.",
    "¿Otra temporada más sin playoffs en New Orleans?",
    "Ante la franquicia neoyorquina, Zion Williamson (33 puntos y 7 rebotes) volvió a demostrar una vez más su potencial de súper-estrella.",
    "Memphis Grizzlies (50%), Portland Trail Blazers (89%) y Dallas Mavericks (92%) se sitúan inmediatamente por encima.",
    "Nuestra campaña de crowdfunding lanzada en febrero de 2013 recibió el apoyo suficiente para salir adelante y así garantizar la continuidad de la web hasta el término de la temporada 2013-14.",
    "El día de la publicación también se enviará un mensaje en Twitter desde la cuenta de @nbamaniacs y en Facebook desde la cuenta @nbamaniacs enlazando al post promocional.",
    "nbamaniacs es un medio citado y enlazado por diversos medios de prestigio como Yahoo! Sports, Marca, AS, ABC, Movistar+, Cuatro, SLAM, HoopsHype o Bleacher Report.",
    "Tu visita a https://www.nbamaniacs.com está sujeta a la presente Política de Privacidad sobre Tratamiento de Datos Personales.",
    "¿Quién almacena los datos?",
    "Avenida Amazonas Central, 2-4 Aranjuez 28300 Madrid (España)",
    "Identidad del controlador y procesador 1: Memberful, LLC (suscripciones).",
    "De acuerdo a lo establecido en el reglamento general de protección de datos europeo (RGPD) 2016/679, Elio Martínez Ortega (nbamaniacs) será responsable del tratamiento de los datos correspondientes a Usuarios de la web.",
    "Google Analytics: un servicio analítico de web prestado por Google, Inc., una compañía de Delaware cuya oficina principal está en 1600 Amphitheatre Parkway, Mountain View (California), CA 94043, Estados Unidos (“Google”). Google Analytics utiliza “cookies”, que son archivos de texto ubicados en tu ordenador, para ayudar a https://www.nbamaniacs.com a analizar el uso que hacen los usuarios del sitio web",
    "Documento actualizado el 17-06-2020.",
    "¿Qué cookies se utilizan en este sitio Web?",
    "Si se trata de un medio impreso basta con la mención del nombre de nbamaniacs y la url general del mismo.",
    "Esa idea se mantuvo a partir de marzo de 2011 cuando un equipo de periodistas y escritores se unieron al proyecto.",
    "Los de Tom Thibodeau salieron en modo rodillo y anotaron 10 puntos consecutivos para igualar la mejor racha de la franquicia desde marzo de 2014 y ascender a la 4ª posición de la Conferencia Este.",
    "Por su parte, Reggie Bullock agregó 18 tantos y seis triples, y R.J. Barrett completó con 16 puntos, 6 rebotes y 5 asistencias.",
    "Los Knicks se colocan cuartos del Este con un registro de 33-27; y los Hawks caen a la quinta plaza con un 32-27.",
    "Stephen Curry cree que tiene que ser el MVP de la temporada.",
    "¿Puede cambiar la policía tras la condena al agente que mató a George Floyd?",
    "En primer lugar, el movimiento Black Lives Matter (BLM), que ya venía luchando por la justicia y la igualdad y contra el desproporcionado número de asesinatos de personas negras a manos de la policía, ha impulsado un nuevo movimiento masivo de protestas a favor de los derechos civiles desde Minneapolis hasta el resto de Estados Unidos y del mundo.",
    "En el juicio a Chauvin por asesinato, Arradondo fue uno de los testigos estrella de la acusación, junto a varios policías de Minneapolis en activo que testificaron contra su excompañero.",
    "Desde que George Floyd fue asesinado el 25 de mayo de 2020 no ha habido ningún cambio revolucionario en la justicia racial de EEUU ni en la actuación policial.",
    "Traducido por Francisco de Zárate.",
    "El debut de ZA/UM crea un universo en donde las identidades del protagonista se enfrentan entre sí de la misma forma que chocan las diferentes ideologías: constantemente tratando de imponerse; buscando seducirnos para que nos dejemos llevar.",
    "Dogen: «Si una frase quiere desgarrarte el alma mi trabajo es hacer que la traducción te la desgarre también».",
    "Entrevistamos al equipo que tradujo al castellano el millón de palabras que componen el debut del estudio estonio-inglés.",
    "Jeanne-Marie —la hermosa Jeanne-Marie, como se refiere a ella el propio título— solía preferir a Arnoux hasta que, tras volver irreconocible de la guerra, acabó por marcharse de la mano de Martin.",
    "¿Videojuegos apolíticos?: Una pequeña reflexión.",
    "La aplicación de los valores que nos forman como personas políticas están dentro de nosotros en nuestro ADN social.",
    "Vamos con las presentaciones: Scrambler parece ser la nueva compañía de Beau Blyth, el creador de Samurai Gunn, que trabajó también en Hyper Light Drifter y que hace unos años firmaba como Teknopants. Peow Studio es gente (buena, según una autoridad en la materia como es el amigo pollomuerto) del mundo del cómic, que precisamente se encargará de llevar los personajes de Samurai Gunn 2 a las viñetas.",
    "Su barba retorcida se convierte en un logotipo que nos encontramos en varios puntos de la arquitectura, como indicador en el mapa y en las monedas de oro.",
    "Lo que convierte a Hades en el Mejor Juego Indie y el Mejor Juego de Acción de 2020 es la sensación de recompensa perpetua acompañada de mamporros frenéticos, diálogos ingeniosos y una narrativa de prioridad conversacional.",
    "Según si miramos los datos de una asesoría u otra, de un país o del siguiente, las mejores cifras del 2020 las consiguieron títulos como Call of Duty: Black Ops: Cold War, Call of Duty: Modern Warfare, Animal Crossing: New Horizons o Cyberpunk 2077.",
    "La etiqueta #HadesGame en Instagram agrupa más de 22.000 publicaciones, siendo la mayoría de ellas creaciones por y para fans.",
    "#hadesgame #hadesfanart #newwallscroll",
    "A pesar de que el juego se centra en el combate, las ideas más reflejadas por sus propios fans giran alrededor de la familia, las relaciones amorosas/sexuales y el propio concepto de héroe.",
    "Hades ya permite cross-saving entre Switch y PC.",
    "¿Un juego casi perfecto que queremos alzar al Olimpo de los juegos perfectos? Métele un 10, que no se diga.",
    "Como os habréis fijado, las notas (excepto las menores de 5) están agrupadas de dos en dos.",
    "En el caso de copiar parcialmente un contenido, se exige que se cite la fuente como AnaitGames, poniendo un link a http://www.anaitgames.com en el caso de ser una página web, o escribiendo la dirección en el caso de una publicación impresa o multimedia.",
    "Para dar cumplimiento a lo establecido en la Ley 34/2002, de 11 de julio, de servicios de la sociedad de la información y de comercio electrónico, a continuación se indican los datos de información general de este sitio web.",
    "El titular del Web empleará todos los esfuerzos y medios razonables para facilitar información actualizada y fehaciente en el Web, no obstante, el titular del Web no asume ninguna garantía en relación con la ausencia de errores, o de posibles inexactitudes y/u omisiones en ninguno de los contenidos accesibles a través de este Web.",
    "¿Puede un videojuego cambiar tu forma de ver el mundo?",
    "Nuestro nuevo libro explora, a través de las voces más autorizadas de la academia y la crítica, cómo los videojuegos representan, exploran y en última instancia influyen en nuestro día a día, nuestras sociedades y nuestra manera de relacionarnos.",
    "Coordina y edita el volumen Marina Amores, periodista (Edge, Revista SFX) y autora de los documentales Mujeres+Videojuegos y Detrás del juego.",
    "Firman los artículos Marta Trivi (periodista; Verne, AnaitGames), Laura Gómez (periodista; Buzzfeed), María Pérez (diseñadora y crítica; TodasGamers, AntiHype), África Curiel (guionista; Ubisoft Blue Byte), Andrea Sacchi (desarrolladora; Tahutahu Studios), Isabel Cano (profesora de desarrollo de videojuegos), Paz Boris (periodista; Games Tribune), Judit Tur (traductora especializada en videojuegos), Diana P. Gómez (productora y responsable del programa de divulgación Cultura Fan), Irene Alvarado (programadora y diseñadora) y Nerea «Nercromina» Díaz (jugadora profesional de Street Fighter).",
    "¿Qué te llevó a trabajar en videojuegos? ¿Siempre tuviste en mente los videojuegos como carrera o como forma de expresión?",
    "Algunos de mis antiguos amigos de Nueva York me animaron a hacer videojuegos.",
    "Gran parte de la poesía que me ha influido está escrita por gente como Elizabeth Bishop, Frank O’Hara, Ted Berrigan y otros poetas que escribieron sobre la gente y la vida común.",
    "Me alegro de haber sido capaz de hacer que la gente hablara sobre sexualidad, sobre todo en la cultura americana, donde es prácticamente tabú hablar de sexo de una manera sincera.",
    "Si Cibele no hubiera sido un MMORPG [massively multiplayer online role-playing game; videojuego de rol multijugador masivos en línea; NdT], ¿habrías contado la historia en otro formato?",
    "Eso sin duda me animó.",
    "En Tacoma, en concreto, hice diseño de niveles para entornos en 3D y en primera persona. En mi trabajo personal hago principalmente 2D, o a veces solo texto sencillo.",
    "Archivado en:¡Protesto!",
    "2019 © Editorial AnaitGames",
    "¿Cuáles son las principales referencias de tu trabajo? ¿Cuándo elegiste el net art, y por qué?",
    "En realidad considero que todas las artes visuales son interactivas, y no hago esa distinción entre las distintas formas [de expresión].",
    "¡Intentaría evitar el software propietario y haría que todavía se pudiera ejecutar!",
    "Fue creado en un momento en el que Google aún no había monopolizado por completo el campo de los motores de búsqueda, y podías intentar encontrar distintos resultados en diferentes buscadores.",
    "Busqué en bases de datos online en busca de vídeos, intentando eludir los sesgos algorítmicos del buscador, y rescaté vídeos perdidos en la cacofonía, enterrados por los algoritmos secretos en favor de información más «compartible».",
    "El estudio madrileño Protocol Games y su publisher, Raiser Games, han anunciado que Song of Horror, llegará finalmente a PlayStation 4 y Xbox One el próximo 28 de mayo. La fecha llega con un nuevo tráiler que podéis ver sobre estas líneas.",
    "Pero la situación toma un cariz aún más oscuro cuando uno echa la vista atrás, tampoco mucho, basta con 11 o 12 años, y se da cuenta de que ese empobrecimiento creativo no se limita a una reiteración de fórmulas o a una comprensión demasiado liberal de la idea de inspiración o influencia, sino va todavía más lejos y pasa por, en realidad, haber cedido parte del terreno ya ganado.",
    "Y, de hecho, su deriva en los últimos tiempos y las fórmulas que ha adoptado también evidencian el proceso: donde antes el terror era en realidad una etiqueta genérica que podía aparecer en combinación a, en realidad, muchos perfiles de videojuego como la aventura gráfica (Shadow of the Comet, Phantasmagoria, la saga Gabriel Knight), la acción (Castlevania, DOOM, FEAR) o el celebrado survival horror (Project Zero, Resident Evil, Dino Crisis); en los últimos años había parecido quedar recluido en el encorsetadísimo molde de los clones de Amnesia, es decir, juegos de terror en primera persona basados en puzzles contextuales y pérdida de todas las opciones defensivas en favor de sigilo.",
    "Con esfuerzo y talento lo consiguieron, y se llama Song of Horror.",
    "En Protocol Games querían hacer un survival horror clásico, veían en juegos como Silent Hill una serie de cualidades que esa prisión autoimpuesta de lo Amnesia-like no podía llegar a realizar.",
    "La dirección de arte, generalmente sobria y espartana, encaja perfectamente con el estilo de terror que busca canalizar, menos próximo, al menos en principio, al terror cósmico más extravagante, y más cercana al terror gótico y sobrenatural de corte más clásico a lo Mary Shelley o Edgar Allan Poe (que, de hecho, pone nombre al nivel de dificultad estándar).",
    "El nuevo tráiler de Shin Megami Tensei III Nocturne HD Remaster va de «facciones y elecciones».",
    "Sé poquito sobre la saga y absolutamente nada sobre esta entrega, pero entiendo que aquí nos quieren hacer la pinza: todos somos fans de Atlus después de Persona 5 y habrá que ponerse un poco al día, digo yo, para cuando por fin salga ese Shin Megami Tensei V de Switch —este mismo año, si nada se tuerce.",
    "Atlus —esto es, ¡SEGA!— ha publicado un nuevo tráiler de Shin Megami Tensei III Nocturne HD Remaster, la «versión modernizada del aclamado clásico» para PS2 que el 25 de mayo llega a Steam, PS4 y Switch.",
    "Me gusta el tráiler, en cualquier caso, y me apetece confiar en unos diseños que siguen resultando moderadamente atractivos dieciocho añazos después de que el juego se estrenara. También es verdad que algunas texturas se podrían haber restaurado un poco mejor («PVPR: 49.99€») y que a los amigos del PC no les entusiasma eso de limitar el framerate a 30 fps.",
    "Hay una librería en Revachol, cerca del hostal Whirling-in-Rags, llamada Crime, Romance & Biographies of Famous People.",
    "Los libros le están esperando». Plaisance (en francés, «placer») es tan culpable como el resto: sus libros son opio para el pueblo.",
    "¿Y juegos? Alguno cabe, claro. Hemos estado dándole a Cozy Grove y a Say No! More, por ejemplo.",
    "Suscríbete en iTunes o Spotify para automatizar todo lo que viene siendo el proceso de descargar nuestra mandanga.",
    "Red Dead Redemption 2 Edición Definitiva 34,99 €.",
    "The Witcher 3: Wild Hunt GOTY 9,99 €.",
    "Yooka-Laylee and the Impossible Lair 10,49 €.",
    "Desde el jueves 22 de abril a las 16:00 (horario peninsular español), están disponibles los desafíos y misiones de la Semana 6, Temporada 6 de Fortnite Battle Royale.",
    "Además, deberías ir a Ajustes > Sonido > Visualizar efectos de sonido y activar Visualizar efectos de sonido.",
    "En este vídeo comparativo podemos ver las principales diferencias entre NieR Replicant ver.1.22474487139... y el Nier original publicado en PS3 en el año 2010.",
    "Estas curvas poli-Bézier pueden ser observadas en el formato de archivo SVG.",
    "Donald Knuth: Metafont: the Program, Addison-Wesley 1986, pp. 123-131. Excellent discussion of implementation details; available for free as part of the TeX distribution.",
    "Paul Bourke: Bézier curves, https://web.archive.org/web/20060708162825/http://astronomy.swin.edu.au/Epbourke/curves/bezier/.",
    "La Playa de las Arenas es una playa de Vélez-Málaga, en la Costa del Sol Oriental de la provincia de Málaga, Andalucía, España.",
    "Ella es bilingüe, habla con fluidez el hebreo, ruso, francés e inglés.",
    "«Full Game of Thrones cast». IMDb (en inglés). Consultado el 5 de noviembre de 2017.",
    "Su denominación comercial más difundida es la inglesa «red claw», que significa literalmente «pinza roja».",
    "Vrbovo es una localidad de Croacia en el municipio de Hrašćina, condado de Krapina-Zagorje.",
    "En 2006 ficha por la cadena de la Conferencia Episcopal Popular TV, donde presenta Sketch & Co., El diccionario popular, La noche de Andrés Caparrós, Qué calor e ¿Y tú de qué vas?.",
    "© Sociedad Estatal Correos y Telegrafos, S.A., S.M.E. Todos los derechos reservados."
    ]
text = ""
for i in range(5):
    text += random.choice(dictionary) + " "
Font.newTab(text)

print("Tab with Real* Spanish text opened.")
